logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    fr.ciadlab: INFO
  file:
    path: /var/log/tomcat9

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format-sql: true
        auto_quote_keyword: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labmanager?serverTimezone=UTC
    username: ciadlabwpbdd
    password: ci@dlAbpas$

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /LabManagerApi

management:
  endpoint:
    logfile:
      enabled: true
      external-file: /var/log/tomcat9/LabManagerApi.log
  endpoints:
    enabled-by-default: true
    web:
      base-path: /management
      exposure:
        include: "*"
  security:
    enabled: false
    roles: ROLE_ADMIN

labmanager:
  default-organization: CIAD
  init:
    enable: true
    data-source: /var/www/ciad-lab.fr/
  file:
    upload-directory: /var/www/ciad-lab.fr/
  web:
    publish-resources: /var/www/ciad-lab.fr/Downloadables/
  debug: false
